"""
Summary Service - Business Logic Layer

Provides framework-agnostic business logic for AI-generated summary management.
Orchestrates summary lifecycle, validation, and analytics following Clean Architecture
Layer 2 principles with comprehensive business rule enforcement.

This service integrates with the prompt builder workflow by managing summaries
generated by AI agents and providing retrieval capabilities for GUI display.
"""

from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from ..models.summary import Summary
from ..repositories.chunk_repository import ChunkRepository
from ..repositories.document_repository import DocumentRepository
from ..repositories.summary_repository import SummaryRepository


class SummaryError(Exception):
    """Domain-specific exception for summary business logic failures."""

    def __init__(self, message: str, cause: Exception = None):
        super().__init__(message)
        self.cause = cause


class SummaryService:
    """
    Summary business logic service.

    Responsibilities:
    - Orchestrate summary lifecycle (create, retrieve, update, delete)
    - Enforce summary business rules and validation
    - Manage summary types and content quality standards
    - Provide summary analytics and statistics
    - Coordinate with chunk/document services for content validation
    - Support AI agent workflow integration

    Does NOT:
    - Know about MCP protocol or GUI frameworks
    - Directly access database or external APIs
    - Implement AI generation logic (delegates to external agents)
    - Handle file system operations

    Clean Architecture Layer 2: Business Logic
    Dependencies: Repository abstractions only (DIP compliance)
    """

    # Business Rule Constants
    SUMMARY_TYPES = {
        "brief": {"min_words": 80, "max_words": 150, "description": "Brief overview"},
        "standard": {"min_words": 200, "max_words": 400, "description": "Standard summary"},
        "detailed": {"min_words": 400, "max_words": 800, "description": "Comprehensive analysis"}
    }

    MAX_CONTENT_LENGTH = 15000  # Maximum characters in summary content
    MIN_CONTENT_LENGTH = 50     # Minimum meaningful content
    MAX_SUMMARIES_PER_CHUNK = 10  # Prevent summary spam

    # Supported AI models for validation
    SUPPORTED_MODELS = {
        "gpt-4", "gpt-4-turbo", "gpt-3.5-turbo",
        "claude-3-opus", "claude-3-sonnet", "claude-3-haiku",
        "gemini-pro", "gemini-1.5-pro",
        "local-llama", "local-mistral",
        "unknown"  # Fallback for testing/development
    }

    def __init__(
        self,
        summary_repository: SummaryRepository,
        chunk_repository: ChunkRepository,
        document_repository: DocumentRepository
    ):
        """
        Initialize service with repository dependencies.

        Args:
            summary_repository: Summary data access abstraction
            chunk_repository: Chunk data access for validation
            document_repository: Document data access for validation
        """
        self.summary_repository = summary_repository
        self.chunk_repository = chunk_repository
        self.document_repository = document_repository

    def save_summary(
        self,
        content: str,
        summary_type: str,
        chunk_id: Optional[int] = None,
        document_id: Optional[int] = None,
        model_name: str = "unknown",
        metadata: Optional[Dict[str, Any]] = None,
        overwrite_existing: bool = False
    ) -> Dict[str, Any]:
        """
        Save AI-generated summary with comprehensive validation.

        Primary method for AI agent workflow - called after agents generate summaries.

        Business Logic:
        1. Validate summary type and content quality
        2. Ensure exactly one of chunk_id or document_id provided
        3. Verify target chunk/document exists
        4. Check for duplicate summaries (unless overwrite)
        5. Create and persist summary with metadata
        6. Return success response with summary details

        Args:
            content: Summary content in markdown format
            summary_type: Type of summary ("brief", "standard", "detailed")
            chunk_id: Target chunk ID (mutually exclusive with document_id)
            document_id: Target document ID (mutually exclusive with chunk_id)
            model_name: AI model used for generation
            metadata: Additional metadata (focus areas, generation params, etc.)
            overwrite_existing: Replace existing summary of same type

        Returns:
            Dictionary with save results and metadata

        Raises:
            ValueError: If validation fails or target not found
            SummaryError: If save operation fails

        Business Rules Enforced:
        - Summary type must be valid with appropriate word count
        - Content must be meaningful and well-formatted markdown
        - Exactly one target (chunk or document) required
        - Target must exist and be accessible
        - No duplicate summaries unless explicitly allowed
        - Model name must be recognized
        """
        # Business Rule: Validate summary type
        if summary_type not in self.SUMMARY_TYPES:
            raise ValueError(
                f"Invalid summary type '{summary_type}'. "
                f"Supported types: {list(self.SUMMARY_TYPES.keys())}"
            )

        # Business Rule: Validate content
        self._validate_summary_content(content, summary_type)

        # Business Rule: Exactly one target required
        if not chunk_id and not document_id:
            raise ValueError("Either chunk_id or document_id must be provided")
        if chunk_id and document_id:
            raise ValueError("Cannot specify both chunk_id and document_id")

        # Business Rule: Validate AI model
        if model_name not in self.SUPPORTED_MODELS:
            # Log warning but allow (new models may be added)
            pass

        try:
            # Validate target exists and resolve document_id
            target_type = None
            target_title = None
            resolved_document_id = document_id

            if chunk_id:
                chunk = self.chunk_repository.get_by_id(chunk_id)
                if not chunk:
                    raise ValueError(f"Chunk {chunk_id} not found")
                target_type = "chunk"
                target_title = chunk.title
                resolved_document_id = chunk.document_id  # Get document_id from chunk
            else:
                assert document_id is not None  # Validated above
                document = self.document_repository.get_by_id(document_id)
                if not document:
                    raise ValueError(f"Document {document_id} not found")
                target_type = "document"
                target_title = document.title

            # Business Rule: Check for duplicate summaries
            assert resolved_document_id is not None  # Should be resolved by now
            if chunk_id:
                existing_summary = self.summary_repository.get_summary_by_type(
                    document_id=resolved_document_id,
                    summary_type=summary_type,
                    chunk_id=chunk_id
                )
                existing_summaries = [existing_summary] if existing_summary else []
            else:
                existing_summary = self.summary_repository.get_summary_by_type(
                    document_id=resolved_document_id,
                    summary_type=summary_type,
                    chunk_id=None
                )
                existing_summaries = [existing_summary] if existing_summary else []

            if existing_summaries and not overwrite_existing:
                raise ValueError(
                    f"Summary of type '{summary_type}' already exists for {target_type}. "
                    f"Use overwrite_existing=True to replace"
                )

            # Business Rule: Check summary count limit
            if chunk_id:
                all_summaries = self.summary_repository.get_by_chunk_id(chunk_id)
            else:
                all_summaries = self.summary_repository.get_by_document_id(resolved_document_id)
            if len(all_summaries) >= self.MAX_SUMMARIES_PER_CHUNK:
                raise SummaryError(
                    f"Maximum {self.MAX_SUMMARIES_PER_CHUNK} summaries per target exceeded"
                )

            # Calculate content metrics
            word_count = len(content.split())

            # Create summary entity (follow domain rule: either document_id OR chunk_id)
            summary = Summary(
                chunk_id=chunk_id,
                document_id=document_id if not chunk_id else None,
                summary_type=summary_type,
                summary_content=content.strip(),
                word_count=word_count,
                model_name=model_name,
                metadata=metadata or {},
                generation_date=datetime.now()
            )

            # Handle existing summary replacement
            if existing_summaries and overwrite_existing:
                existing_summary = existing_summaries[0]
                summary.id = existing_summary.id
                created_summary = self.summary_repository.update(summary)
                action = "updated"
            else:
                created_summary = self.summary_repository.create(summary)
                action = "created"

            # Prepare success response
            result = {
                "success": True,
                "action": action,
                "summary_id": created_summary.id,
                "summary_type": summary_type,
                "target_type": target_type,
                "target_id": chunk_id or resolved_document_id,
                "target_title": target_title,
                "word_count": word_count,
                "model_name": model_name,
                "generation_date": summary.generation_date.isoformat() if summary.generation_date else None,
                "content_preview": content[:100] + "..." if len(content) > 100 else content
            }

            return result

        except Exception as e:
            if isinstance(e, (ValueError, SummaryError)):
                raise
            raise SummaryError(f"Failed to save summary: {str(e)}") from e

    def get_summary(self, summary_id: int) -> Optional[Dict[str, Any]]:
        """
        Retrieve summary by ID with full content and metadata.

        Args:
            summary_id: Summary ID to retrieve

        Returns:
            Dictionary with summary details or None if not found
        """
        summary = self.summary_repository.get_by_id(summary_id)
        if not summary:
            return None

        return self._summary_to_dict(summary)

    def get_summaries_for_chunk(self, chunk_id: int) -> List[Dict[str, Any]]:
        """
        Get all summaries for a specific chunk.

        Critical for prompt builder workflow - shows existing summaries in GUI.

        Args:
            chunk_id: Chunk to get summaries for

        Returns:
            List of summary dictionaries

        Raises:
            ValueError: If chunk doesn't exist
        """
        # Validate chunk exists
        chunk = self.chunk_repository.get_by_id(chunk_id)
        if not chunk:
            raise ValueError(f"Chunk {chunk_id} not found")

        summaries = self.summary_repository.get_by_chunk_id(chunk_id)
        return [self._summary_to_dict(summary) for summary in summaries]

    def get_summaries_for_document(self, document_id: int) -> List[Dict[str, Any]]:
        """
        Get all summaries for a specific document.

        Args:
            document_id: Document to get summaries for

        Returns:
            List of summary dictionaries

        Raises:
            ValueError: If document doesn't exist
        """
        # Validate document exists
        document = self.document_repository.get_by_id(document_id)
        if not document:
            raise ValueError(f"Document {document_id} not found")

        summaries = self.summary_repository.get_by_document_id(document_id)
        return [self._summary_to_dict(summary) for summary in summaries]

    def list_summaries(
        self,
        filters: Optional[Dict[str, Any]] = None,
        sort_by: str = "generation_date",
        sort_order: str = "desc",
        limit: int = 50,
        offset: int = 0
    ) -> List[Dict[str, Any]]:
        """
        List summaries with filtering, sorting, and pagination.

        Args:
            filters: Optional filters (summary_type, model_name, date_from, date_to)
            sort_by: Field to sort by
            sort_order: Sort order ("asc" or "desc")
            limit: Maximum results to return
            offset: Results to skip for pagination

        Returns:
            List of summary dictionaries

        Raises:
            ValueError: If pagination parameters invalid
        """
        # Business Rule: Validate pagination
        if limit > 500:
            raise ValueError("Limit cannot exceed 500")
        if offset < 0:
            raise ValueError("Offset must be non-negative")

        # Apply filtering and pagination
        filter_params = filters or {}
        filter_params.update({
            "sort_by": sort_by,
            "sort_order": sort_order,
            "limit": limit,
            "offset": offset
        })

        summaries = self.summary_repository.list_all(filter_params)
        return [self._summary_to_dict(summary, include_content=False) for summary in summaries]

    def update_summary(
        self,
        summary_id: int,
        content: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Update existing summary content or metadata.

        Args:
            summary_id: Summary to update
            content: New content (if provided)
            metadata: Updated metadata (if provided)

        Returns:
            Dictionary with update results

        Raises:
            ValueError: If summary not found or validation fails
            SummaryError: If update operation fails
        """
        # Validate summary exists
        summary = self.summary_repository.get_by_id(summary_id)
        if not summary:
            raise ValueError(f"Summary {summary_id} not found")

        try:
            updated = False

            # Update content if provided
            if content is not None:
                self._validate_summary_content(content, summary.summary_type)
                summary.summary_content = content.strip()
                summary.word_count = len(content.split())
                updated = True

            # Update metadata if provided
            if metadata is not None:
                summary.metadata = metadata
                updated = True

            if not updated:
                raise ValueError("No updates provided")

            # Persist changes
            updated_summary = self.summary_repository.update(summary)

            return {
                "success": True,
                "summary_id": updated_summary.id,
                "word_count": updated_summary.word_count
            }

        except Exception as e:
            if isinstance(e, (ValueError, SummaryError)):
                raise
            raise SummaryError(f"Failed to update summary: {str(e)}") from e

    def delete_summary(self, summary_id: int) -> Dict[str, Any]:
        """
        Delete summary with cleanup.

        Args:
            summary_id: Summary to delete

        Returns:
            Dictionary with deletion results

        Raises:
            ValueError: If summary not found
            SummaryError: If deletion fails
        """
        # Validate summary exists
        summary = self.summary_repository.get_by_id(summary_id)
        if not summary:
            raise ValueError(f"Summary {summary_id} not found")

        try:
            # Perform deletion
            success = self.summary_repository.delete(summary_id)

            if not success:
                raise SummaryError(f"Failed to delete summary {summary_id}")

            return {
                "success": True,
                "summary_id": summary_id,
                "deleted_at": datetime.now().isoformat()
            }

        except Exception as e:
            if isinstance(e, (ValueError, SummaryError)):
                raise
            raise SummaryError(f"Failed to delete summary: {str(e)}") from e

    def delete_summaries_for_target(
        self,
        chunk_id: Optional[int] = None,
        document_id: Optional[int] = None
    ) -> Dict[str, Any]:
        """
        Delete all summaries for a chunk or document.

        Used during chunk/document deletion for cleanup.

        Args:
            chunk_id: Chunk ID to clean up summaries for
            document_id: Document ID to clean up summaries for

        Returns:
            Dictionary with deletion results

        Raises:
            ValueError: If neither target specified
        """
        if not chunk_id and not document_id:
            raise ValueError("Either chunk_id or document_id must be provided")

        try:
            # Delete summaries for target
            if chunk_id:
                deleted_count = self.summary_repository.delete_by_chunk_id(chunk_id)
                target_type = "chunk"
                target_id = chunk_id
            else:
                # document_id is guaranteed to be not None by validation above
                assert document_id is not None
                deleted_count = self.summary_repository.delete_by_document_id(document_id)
                target_type = "document"
                target_id = document_id

            return {
                "success": True,
                "target_type": target_type,
                "target_id": target_id,
                "summaries_deleted": deleted_count,
                "deleted_at": datetime.now().isoformat()
            }

        except Exception as e:
            raise SummaryError(f"Failed to delete summaries: {str(e)}") from e

    def get_summary_statistics(self) -> Dict[str, Any]:
        """
        Get comprehensive summary statistics for system monitoring.

        Returns:
            Dictionary with aggregated statistics
        """
        try:
            # Get all summaries for analysis
            all_summaries = self.summary_repository.list_all()

            if not all_summaries:
                return {
                    "total_summaries": 0,
                    "summaries_by_type": {},
                    "summaries_by_model": {},
                    "average_word_count": 0,
                    "total_words_summarized": 0,
                    "recent_summaries_7d": 0,
                    "recent_summaries_30d": 0
                }

            # Calculate statistics
            total_summaries = len(all_summaries)

            # Group by summary type
            by_type = {}
            for summary in all_summaries:
                summary_type = summary.summary_type
                by_type[summary_type] = by_type.get(summary_type, 0) + 1

            # Group by model
            by_model = {}
            for summary in all_summaries:
                model = summary.model_name
                by_model[model] = by_model.get(model, 0) + 1

            # Word count statistics
            word_counts = [s.word_count for s in all_summaries if s.word_count]
            total_words = sum(word_counts)
            avg_words = total_words / len(word_counts) if word_counts else 0

            # Recent summaries
            now = datetime.now()
            seven_days_ago = now - timedelta(days=7)
            thirty_days_ago = now - timedelta(days=30)

            recent_7d = len([s for s in all_summaries if s.generation_date and s.generation_date >= seven_days_ago])
            recent_30d = len([s for s in all_summaries if s.generation_date and s.generation_date >= thirty_days_ago])

            # Content quality metrics
            quality_stats = self._analyze_content_quality(all_summaries)

            return {
                "total_summaries": total_summaries,
                "summaries_by_type": by_type,
                "summaries_by_model": by_model,
                "average_word_count": round(avg_words, 1),
                "total_words_summarized": total_words,
                "recent_summaries_7d": recent_7d,
                "recent_summaries_30d": recent_30d,
                "content_quality": quality_stats,
                "statistics_generated_at": now.isoformat()
            }

        except Exception as e:
            raise SummaryError(f"Failed to generate statistics: {str(e)}") from e

    def validate_summary_type(self, summary_type: str) -> Dict[str, Any]:
        """
        Validate summary type and return requirements.

        Args:
            summary_type: Type to validate

        Returns:
            Dictionary with validation results and requirements
        """
        if summary_type not in self.SUMMARY_TYPES:
            return {
                "valid": False,
                "summary_type": summary_type,
                "error": f"Invalid summary type. Supported: {list(self.SUMMARY_TYPES.keys())}",
                "supported_types": list(self.SUMMARY_TYPES.keys())
            }

        type_info = self.SUMMARY_TYPES[summary_type]
        return {
            "valid": True,
            "summary_type": summary_type,
            "min_words": type_info["min_words"],
            "max_words": type_info["max_words"],
            "description": type_info["description"],
            "content_requirements": [
                f"Word count: {type_info['min_words']}-{type_info['max_words']} words",
                "Valid markdown format",
                "Meaningful content with proper structure",
                "Clear topic focus and key insights"
            ]
        }

    def _validate_summary_content(self, content: str, summary_type: str) -> None:
        """
        Validate summary content against business rules.

        Args:
            content: Content to validate
            summary_type: Expected summary type

        Raises:
            ValueError: If content validation fails
        """
        if not content or not content.strip():
            raise ValueError("Summary content cannot be empty")

        # Content length validation
        if len(content) < self.MIN_CONTENT_LENGTH:
            raise ValueError(f"Summary content too short (minimum {self.MIN_CONTENT_LENGTH} characters)")

        if len(content) > self.MAX_CONTENT_LENGTH:
            raise ValueError(f"Summary content too long (maximum {self.MAX_CONTENT_LENGTH} characters)")

        # Word count validation for type
        word_count = len(content.split())
        type_info = self.SUMMARY_TYPES[summary_type]

        if word_count < type_info["min_words"]:
            raise ValueError(
                f"{summary_type} summary must be at least {type_info['min_words']} words "
                f"(current: {word_count})"
            )

        if word_count > type_info["max_words"]:
            raise ValueError(
                f"{summary_type} summary cannot exceed {type_info['max_words']} words "
                f"(current: {word_count})"
            )

        # Basic markdown validation
        if content.count('```') % 2 != 0:
            raise ValueError("Unmatched code blocks in markdown content")

    def _summary_to_dict(self, summary: Summary, include_content: bool = True) -> Dict[str, Any]:
        """
        Convert Summary model to dictionary representation.

        Args:
            summary: Summary model to convert
            include_content: Whether to include full content

        Returns:
            Dictionary representation
        """
        result = {
            "summary_id": summary.id,
            "chunk_id": summary.chunk_id,
            "document_id": summary.document_id,
            "summary_type": summary.summary_type,
            "word_count": summary.word_count,
            "model_name": summary.model_name,
            "metadata": summary.metadata,
            "generation_date": summary.generation_date.isoformat() if summary.generation_date else None
        }

        if include_content:
            result["summary_content"] = summary.summary_content
        else:
            # Provide preview for list views
            content = summary.summary_content or ""
            result["content_preview"] = content[:100] + "..." if len(content) > 100 else content

        return result

    def _analyze_content_quality(self, summaries: List[Summary]) -> Dict[str, Any]:
        """
        Analyze content quality metrics across summaries.

        Args:
            summaries: List of summaries to analyze

        Returns:
            Dictionary with quality metrics
        """
        if not summaries:
            return {"average_quality_score": 0}

        # Simple quality heuristics
        quality_scores = []

        for summary in summaries:
            content = summary.summary_content or ""
            score = 0

            # Length appropriate for type
            type_info = self.SUMMARY_TYPES.get(summary.summary_type, {})
            if type_info:
                word_count = summary.word_count or 0
                if type_info.get("min_words", 0) <= word_count <= type_info.get("max_words", 1000):
                    score += 25

            # Has markdown structure
            if any(marker in content for marker in ['#', '**', '*', '-', '1.']):
                score += 25

            # Has good paragraph structure
            paragraphs = len([p for p in content.split('\n\n') if p.strip()])
            if paragraphs >= 2:
                score += 25

            # No obvious issues
            if not any(issue in content.lower() for issue in ['error', 'failed', 'unable']):
                score += 25

            quality_scores.append(score)

        return {
            "average_quality_score": round(sum(quality_scores) / len(quality_scores), 1),
            "high_quality_summaries": len([s for s in quality_scores if s >= 75]),
            "medium_quality_summaries": len([s for s in quality_scores if 50 <= s < 75]),
            "low_quality_summaries": len([s for s in quality_scores if s < 50])
        }
